name: build

on:
  push:
    branches:
      - main
      - master
  pull_request:
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]

    steps:
        - name: Checkout
          uses: actions/checkout@v2.3.3
          with:
            submodules: recursive
            fetch-depth: 2
            
        - uses: ilammy/msvc-dev-cmd@v1
          with:
           arch: amd64_x86           
        - name: Run setup script        
          shell: cmd
          run: |
            "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/Tools/VsDevCmd.bat" -arch=x86
            .\setup.bat

        - name: Run build script
          shell: cmd
          run: |
            "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" -arch=x86
            .\build.bat
